config/routes.rb
Rails.application.routes.draw do
  concern :lovable do
    resources :hearts, only: [:create, :destroy]
  end

  # sessions
  get "sign_out", to: "sessions#destroy", as: "sign_out"
  resources :sessions, only: [:new, :create] do
    collection do
      get "status"
    end
  end

  # posts
  resources :posts, concerns: :lovable, only: [:index, :create, :show, :destroy] do
    #comments
    resources :comments, only: [:create]
  end

  # comments
  resources :comments, concerns: :lovable, only: [:show, :destroy]

  # photos
  resources :photos, only: [:index, :show] do
    member do
      get "view"
    end
  end

  # resources :users, only: [:show]

  # twilio webhooks
  post "/voice", to: "comms#voice"
  post "/sms", to: "comms#sms"

  # users
  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get "posts"
      get "comments"
      get "hearts"
      get "photos"
    end
  end
#  get "/:id", to: "users#show", as: :user

  # default to posts index
  root "posts#index"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authorize_user
  protect_from_forgery with: :exception
  include Pundit

  private

    def authorize_user
      unless signed_in?
        flash[:notice] = "Please sign in."
        redirect_to new_session_path
      end
    end

    def signed_in?
      current_user.present?
    end
    helper_method :signed_in?

    def current_user
      @current_user ||= User.find_by(auth_token: cookies[:auth_token]) if cookies[:auth_token]
    end
    helper_method :current_user

    def analytics
      @analytics ||= Analytics.new(current_user)
    end

    def twilio
      @twilio = Twilio::REST::Client.new
    end
    helper_method :twilio

    def family_phone_number
      @family_phone_number ||= ENV["FAMILY_PHONE_NUMBER"]
    end
    helper_method :family_phone_number
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    MarkdownService.new.render(text)
  end

  def user_avatar_tag(user, size=50)
    image_tag user.avatar_url, width: size, height: size, class: "avatar"
  end

  def active_path_class(path)
    "active" if viewing_path?(path)
  end

  def viewing_path?(path)
    request.fullpath =~ /#{path}/i
  end
end

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_IO_KEY"] %>
  <script type="text/javascript">
    window.analytics=window.analytics||[],window.analytics.methods=["identify","group","track","page","pageview","alias","ready","on","once","off","trackLink","trackForm","trackClick","trackSubmit"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var key=window.analytics.methods[i];window.analytics[key]=window.analytics.factory(key)}window.analytics.load=function(t){if(!document.getElementById("analytics-js")){var a=document.createElement("script");a.type="text/javascript",a.id="analytics-js",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.io/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)}},window.analytics.SNIPPET_VERSION="2.0.9",
    window.analytics.load("<%= ENV["SEGMENT_IO_KEY"] %>");
    window.analytics.page();
  </script>
<% end %>

app/views/application/_analytics.html.haml
- if ENV["SEGMENT_IO_KEY"]
  :javascript
    window.analytics=window.analytics||[],window.analytics.methods=["identify","group","track","page","pageview","alias","ready","on","once","off","trackLink","trackForm","trackClick","trackSubmit"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var key=window.analytics.methods[i];window.analytics[key]=window.analytics.factory(key)}window.analytics.load=function(t){if(!document.getElementById("analytics-js")){var a=document.createElement("script");a.type="text/javascript",a.id="analytics-js",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.io/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)}},window.analytics.SNIPPET_VERSION="2.0.9",
    window.analytics.load("#{ENV["SEGMENT_IO_KEY"]}");
    window.analytics.page();

app/views/application/_flashes.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/application/_javascript.html.haml
= javascript_include_tag :application
= yield :javascript
= render "analytics"
- if Rails.env.test?
  = javascript_tag do
    $.fx.off = true;
    $.ajaxSetup({ async: false });

app/views/application/_navigation.html.haml
%nav.navbar.navbar-inverse.navbar-static-top{role: "navigation"}
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to root_path, class: "navbar-brand" do
        %span.glyphicon.glyphicon-heart-empty
        Family
    .collapse.navbar-collapse
      - if signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li{class: active_path_class(:posts)}
            = link_to "Posts", posts_path(sort_by: "created_at")
          %li{class: active_path_class(:photos)}
            = link_to "Photos", photos_path
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
              %span.glyphicon.glyphicon-cog
            %ul.dropdown-menu{:role => "menu"}
              %li
                = link_to [:edit, current_user] do
                  %span.glyphicon.glyphicon-user
                  Account
              %li
                = link_to users_path do
                  %span.glyphicon.glyphicon-fire
                  Stats
              %li.divider
              %li
                = link_to sign_out_path do
                  %span.glyphicon.glyphicon-log-out
                  Sign out
      %ul.nav.navbar-nav
        = render "navigation_links"

app/views/application/_navigation_links.html.haml
- if signed_in?
  - %w{John Danielle Renee Scott Brian Wendy}.each do |user|
    %li{class: active_path_class(user)}
      = link_to user, user_path(user.downcase)